### PR TITLE
Add a navbar

### PR DESCRIPTION
**Pull request by twgardner2**
* Sticky navbar
* Overlay for the FAQs

This is definitely not done, but interested to see what you think. I think the styling could use some work. Other issues:

- Opening the FAQ always scrolls the page to the top, it shouldn't do that
- The FAQ should maybe be styled a little better, i.e. by maybe causing some line breaks or something?
- I probably did this is a very messy way in terms of the code. I tried making this work with your very nice `addHTMLTemplates()` function, but couldn't do it. I tried adding the navbar and overlay as their own templates and wanted to add their javascript in a `<script>` tag in their HTML, but that wasn't working for some reason.

### CODE REVIEW

**Comment by ChaseWPDEV** [comment]
I like it. My only note being that we probably need to tighten up the styling to prevent long stretches of text, and check on the contrast to ensure it's sufficiently legible.

**Comment by twgardner2** [comment]
I think this is better, probably good enough to merge to main. Let me know what you think. 

I added the gmail address Kate setup to the navbar. It feels a little clunky to me, interested in your thoughts.

**Comment by twgardner2** [comment]
Thanks for cleaning up my mess :)

**Comment by twgardner2** [comment]
Ready to merge this? Think it needs more work?

**Pull request merged**
