### PR TITLE
Refactor/npm

### PR DESCRIPTION
**Pull request by ChaseWPDEV**
Converted the build process into a npm/webpack workflow to simplify adding packages from the npm universe.

### CODE REVIEW

**Comment by twgardner2** [comment]
I finally had a couple minutes to sit down and look at this. My web knowledge is apparently very atrophied...trying to figure out what I'm looking at ¯\_(ツ)_/¯

**Comment by ChaseWPDEV** [comment]
Fair Question. This PR is primarily a conversion of the project from a series of enqueued scrip tags, to a Webpack bundle project. Basically, it allows us to do things like `npm install` , break code into modules, and use SASS (CSS with unobtrusive enhancements), and webpack "transpiles' it into a browser-friendly format without us needing to think too much about it. (but with source maps, so we can still debug it)

This is the gateway to PDF parsing, Easy on Page Data Entry, and generally manageable project growth.

**Comment by twgardner2** [comment]
Awesome, sounds amazing.

Either I'm a dumb or I need to update something in my environment - any thoughts?:

image

Do I need to install `webpack` globally or something?

I can run webpack out of `node_modules`, but I'm not sure what it's doing:

image

**Comment by ChaseWPDEV** [comment]
Silly question: Did you run `npm install` to load the modules?

**Comment by twgardner2** [comment]
Ah, yes, I meant to include that on the screenshot. Everything seemed to
install just fine. I'll show you that output when I get home tonight.

**Comment by twgardner2** [comment]
image

**Comment by twgardner2** [comment]
I don't understand why npm isn't finding `webpack`. I can run it manually out of `node_modules/.bin/webpack`

image

**Comment by twgardner2** [comment]
Should it be `npx webpack --mode development`?

image

**Comment by ChaseWPDEV** [comment]
Yes that seems to work. Although, it might work without npx altogether e.g. `webpack --mode development` (not sure if that's from a global I have installed)

**Comment by twgardner2** [comment]
yeah, `webpack` with no `npx` doesn't work for me. I know that's just a `PATH` issue and all, I just though `node`/`npm` would have taken care of everything...

**Pull request merged**
