### PR TITLE
Sum group average

### PR DESCRIPTION
**Pull request by ChaseWPDEV**

### CODE REVIEW

**Comment by ChaseWPDEV** [comment]
Built off the head of the autoCalcAverages branch. Not yet ready to merge, as it only parses from the PDF, and there's no UI to display it--but it's a start.

**Comment by ChaseWPDEV** [comment]
@twgardner2  I think we've got a good release candidate here for the summary group averages comparison. Ready to merge once you've had a chance to review and verify everything looks good.

**Comment by twgardner2** [comment]
This is awesome. Thoughts: 

* Are you seeing that some of the area highlights (shown on top of the FITREPs when hovering over rank/RS/command) are sticking around when they should go away? That has always happened, but they seem to get "locked in" if they are present when you click over onto a different tab. This has always been a problem that I've wanted to fix, but I'm not sure how exactly yet.
  *  Update, I commented out some transitions that were opening the window to the highlight elements getting "stuck". I think this is better, what do you think?    

* I really like the ability to look at the graph in terms of Summary Group Average, but 1-of-1 FITREPs seem to distort it. The inability to do any better than (Trait Average-Summary Group Average)=0 when only compared to yourself seems to cause a lot of downward sloped lines. I don't know what we would do to fix this, maybe it's just inherent in the data underlying Navy FITREPs? Maybe 1-of-1 FITREPs shouldn't be displayed on a plot that focuses on Summary Groups?

* I tried to apply some of the [Navy Brand Colors](https://usnavy.github.io/Navy-Design-Guide/brand-colors.html) for more consistency, let me know what you think

* I see why you left a border on the canvas (to indicate it's tied to the tabs), but how do you feel about the feel with it removed?

**Comment by ChaseWPDEV** [comment]
@twgardner2  I'm good with all the changes.

Re: 1 of 1, I think that's just the nature of the beast with looking at Summary Group Averages. We could _could_ look at making the summary group scale (ie circle radius) more dramatic so there's a more significant visual difference -- but I think that's an idea for a different branch.

I'm good if you are. Let's merge this SOB!

**Pull request merged**
